# hadolint ignore=DL3007
FROM dast1986/slough-dev-dc-cpp:latest AS base

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Configure Starship
ENV PROMPTNAME="ESP32"

# Set the default command to bash
CMD ["bash"]
